FirstTask/Models/Car.cs
namespace FirstTask.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string Color { get; set; }
        public string Engine { get; set; }
        public int Year { get; set; }
        public int ModelId { get; set; }
    }
}

FirstTask/Models/Marka.cs
namespace FirstTask.Models
{
    public class Marka
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

FirstTask/Models/Model.cs
namespace FirstTask.Models
{
    public class Model
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MarkaId { get; set; }
    }
}

FirstTask/Controllers/CarController.cs
using FirstTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstTask.Controllers
{
    public class CarController : Controller
    {
        private readonly List<Car> _cars;

        public CarController()
        {
            _cars = new List<Car>
            {
                new Car{ Id = 1,Color = "Black", Engine = "2.4l", Year = 2014, ModelId = 1 },
                new Car{ Id = 2,Color = "Red", Engine = "3.2l", Year = 2016, ModelId = 1 },
                new Car{ Id = 3,Color = "White", Engine = "3.1l", Year = 2010, ModelId = 2 },
                new Car{ Id = 4,Color = "Brown", Engine = "3.3l", Year = 2011, ModelId = 2 },
                new Car{ Id = 5,Color = "Black", Engine = "2.1l", Year = 2012, ModelId = 3 },
                new Car{ Id = 5,Color = "Yellow", Engine = "2.5l", Year = 2015, ModelId = 3 },
                new Car{ Id = 7,Color = "Green", Engine = "2.7l", Year = 2014, ModelId = 4 },
                new Car{ Id = 8,Color = "Brown", Engine = "2.8l", Year = 2015, ModelId = 4 },
                new Car{ Id = 9,Color = "Red", Engine = "2.35l", Year = 2016, ModelId = 5 },
                new Car{ Id = 10,Color = "Purple", Engine = "2.2l", Year = 2011, ModelId = 5 },
                new Car{ Id = 11,Color = "Yellow", Engine = "3.4l", Year = 2019, ModelId = 6 },
                new Car{ Id = 12,Color = "White", Engine = "2.8l", Year = 2014, ModelId = 6 },
            };
        }
        public IActionResult Index(int? id)
        {
            if (id != null)
            {
                if (_cars.Exists(m => m.ModelId == id)) NotFound();

                return View(_cars.FindAll(m => m.ModelId == id));
            }
            return View(_cars);
        }

        public IActionResult Detail(int? id)
        {
            if (id == null) BadRequest();

            Car car = _cars.Find(c => c.Id == id);

            if (car == null) return NotFound(); 

            return View(car);
        }
    }
}

FirstTask/Controllers/MarkaController.cs
using FirstTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstTask.Controllers
{
    public class MarkaController : Controller
    {
        private readonly List<Marka> _marka;

        public MarkaController()
        {
            _marka = new List<Marka>
            {
                new Marka{ Id = 1, Name = "BMW"},
                new Marka{ Id = 2, Name = "Ferrari"},
                new Marka{ Id = 3, Name = "Mercedes"},
                new Marka{ Id = 4, Name = "Audi"},
            };
        }

        public IActionResult Index()
        {
            return View(_marka);
        }
    }
}

FirstTask/Controllers/ModelController.cs
using FirstTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstTask.Controllers
{
    public class ModelController : Controller
    {
        private readonly List<Model> _models;

        public ModelController()
        {
            _models = new List<Model>
            {
                new Model { Id = 1, Name = "M5", MarkaId= 1 },
                new Model { Id = 2, Name = "M7", MarkaId= 1 },
                new Model { Id = 3, Name = "458 Italia", MarkaId= 2 },
                new Model { Id = 4, Name = "A 250", MarkaId= 3 },
                new Model { Id = 5, Name = "B 170", MarkaId= 3 },
                new Model { Id = 6, Name = "Q7", MarkaId= 4 },
            };
        }
        public IActionResult Index(int? id)
        {
            if (id != null)
            {
                if(_models.Exists(m => m.MarkaId == id)) NotFound();

                return View(_models.FindAll( m => m.MarkaId == id));
            }
            return View(_models);
        }
    }
}

FirstTask/Views/Car/Detail.cshtml
@model Car

<ul class="list-group">
    <li class="list-group-item active" aria-current="true">Year: @Model.Year</li>
    <li class="list-group-item active" aria-current="true">Color: @Model.Color</li>
    <li class="list-group-item active" aria-current="true">Engine: @Model.Engine</li>
</ul>

FirstTask/Views/Car/Index.cshtml
@model List<Car>

<ul class="list-group">
    @foreach (Car car in Model)
    {
        <li class="list-group-item active" aria-current="true">
            <a asp-controller="Car" asp-action="detail" asp-route-id="@car.Id">@car.Year</a>
        </li>
    }
</ul>

FirstTask/Views/Marka/Index.cshtml
@model List<Marka>

<ul class="list-group">
    @foreach (Marka marka in Model)
    {
        <li class="list-group-item active" aria-current="true">
            <a asp-controller="Model" asp-action="index" asp-route-id="@marka.Id">@marka.Name</a>
        </li>
    }
</ul>

FirstTask/Views/Model/Index.cshtml
@model List<Model>

<ul class="list-group">
    @foreach (Model modell in Model)
    {
        <li class="list-group-item active" aria-current="true">
            <a asp-controller="Car" asp-action="index" asp-route-id="@modell.Id">@modell.Name</a>
        </li>
    }
</ul>

FirstTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>